In [142]:
import pandas as pd

In [143]:
name=['a','b','c','d','e']

In [144]:
id=[1,2,3,4,5]

In [145]:
salary=[1000,2000,3000,4000,5000]

In [146]:
df=pd.DataFrame({"name":name,"emp_id":id,"salary":salary})

In [147]:
df

name  emp_id  salary
0    a       1    1000
1    b       2    2000
2    c       3    3000
3    d       4    4000
4    e       5    5000

In [148]:
#numpy

In [149]:
import numpy as np

In [150]:
np.arange(1,21)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [151]:
np.arange(2,22,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [152]:
a=[3,4,5,6]
d1=np.array(a)


In [153]:
d1

array([3, 4, 5, 6])

In [154]:
np.ndim(d1)

1

In [155]:
d2=[[1,2,3],[4,5,6]]
d2=np.array(d2)


In [156]:
d2

array([[1, 2, 3],
       [4, 5, 6]])

In [157]:
np.ndim(d2)

2

In [158]:
l=[[1,2,3]],[[4,5,6]],[[7,8,9]]

In [159]:
d3=np.array(l)

In [160]:
d3

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [161]:
np.ndim(d3)



3

In [162]:
print(len(d3))

3


d3.reshape(3,3)

In [164]:
d3.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [165]:
df.head()

name  emp_id  salary
0    a       1    1000
1    b       2    2000
2    c       3    3000
3    d       4    4000
4    e       5    5000

In [166]:
df=np.arange(1,21).reshape(4,5)
df

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [167]:
df1=pd.DataFrame(data=df,index=["row1","row2","row3","row4"],columns=["C1","C2","C3","C4","C5"])

In [168]:
df

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [169]:
df1

C1  C2  C3  C4  C5
row1   1   2   3   4   5
row2   6   7   8   9  10
row3  11  12  13  14  15
row4  16  17  18  19  20

In [170]:
abc = pd.read_csv("data.csv", encoding="latin1")


In [171]:
abc

Table_Tau                                         Table_name  \
0      Ripanga 1        Te tatauranga o nga umanga – Nga uepu Maori   
1      Ripanga 1        Te tatauranga o nga umanga – Nga uepu Maori   
2      Ripanga 1        Te tatauranga o nga umanga – Nga uepu Maori   
3      Ripanga 1        Te tatauranga o nga umanga – Nga uepu Maori   
4      Ripanga 1        Te tatauranga o nga umanga – Nga uepu Maori   
...          ...                                                ...   
2879  Ripanga 23  Nga raraunga whakawhiwhi mahi umanga –nga tura...   
2880  Ripanga 23  Nga raraunga whakawhiwhi mahi umanga –nga tura...   
2881  Ripanga 23  Nga raraunga whakawhiwhi mahi umanga –nga tura...   
2882  Ripanga 23  Nga raraunga whakawhiwhi mahi umanga –nga tura...   
2883  Ripanga 23  Nga raraunga whakawhiwhi mahi umanga –nga tura...   

         Table_sub_name              Breakdown                      Section  \
0     A-wehenga ahumahi              Ahuwhenua  Nga umanga katoa o Aotearoa   
1     A-wehenga ahumahi              Ahuwhenua  Nga umanga katoa o Aotearoa   
2     A-wehenga ahumahi              Ahuwhenua  Nga umanga katoa o Aotearoa   
3     A-wehenga ahumahi              Ahuwhenua  Nga umanga katoa o Aotearoa   
4     A-wehenga ahumahi              Ahuwhenua  Nga umanga katoa o Aotearoa   
...                 ...                    ...                          ...   
2879  Ma te momo umanga  Tapeke whiwhinga moni               Nga uepu Maori   
2880  Ma te momo umanga  Tapeke whiwhinga moni               Nga uepu Maori   
2881  Ma te momo umanga  Tapeke whiwhinga moni               Nga uepu Maori   
2882  Ma te momo umanga  Tapeke whiwhinga moni               Nga uepu Maori   
2883  Ma te momo umanga  Tapeke whiwhinga moni               Nga uepu Maori   

                           Units  Value Time_Period         Footnotes  
0     Te tatauranga o nga umanga  58656        2012                 1  
1     Te tatauranga o nga umanga  56538        2013                 1  
2     Te tatauranga o nga umanga  56514        2014                 1  
3     Te tatauranga o nga umanga  57174        2015                 1  
4     Te tatauranga o nga umanga  56592        2016                 1  
...                          ...    ...         ...               ...  
2879                  $(miriona)    173     2020_03  1 me 2 me 3 me 4  
2880                  $(miriona)    182     2020_06  1 me 2 me 3 me 4  
2881                  $(miriona)    182     2020_09  1 me 2 me 3 me 4  
2882                  $(miriona)    188     2020_12  1 me 2 me 3 me 4  
2883                  $(miriona)    180     2021_03  1 me 2 me 3 me 4  

[2884 rows x 9 columns]

In [172]:
abc.head()

Table_Tau                                   Table_name     Table_sub_name  \
0  Ripanga 1  Te tatauranga o nga umanga – Nga uepu Maori  A-wehenga ahumahi   
1  Ripanga 1  Te tatauranga o nga umanga – Nga uepu Maori  A-wehenga ahumahi   
2  Ripanga 1  Te tatauranga o nga umanga – Nga uepu Maori  A-wehenga ahumahi   
3  Ripanga 1  Te tatauranga o nga umanga – Nga uepu Maori  A-wehenga ahumahi   
4  Ripanga 1  Te tatauranga o nga umanga – Nga uepu Maori  A-wehenga ahumahi   

   Breakdown                      Section                       Units  Value  \
0  Ahuwhenua  Nga umanga katoa o Aotearoa  Te tatauranga o nga umanga  58656   
1  Ahuwhenua  Nga umanga katoa o Aotearoa  Te tatauranga o nga umanga  56538   
2  Ahuwhenua  Nga umanga katoa o Aotearoa  Te tatauranga o nga umanga  56514   
3  Ahuwhenua  Nga umanga katoa o Aotearoa  Te tatauranga o nga umanga  57174   
4  Ahuwhenua  Nga umanga katoa o Aotearoa  Te tatauranga o nga umanga  56592   

  Time_Period Footnotes  
0        2012         1  
1        2013         1  
2        2014         1  
3        2015         1  
4        2016         1

In [173]:
abc.describe()

Table_Tau                                         Table_name  \
count        2884                                               2884   
unique         23                                                 23   
top     Ripanga 3  Tatauranga o nga umanga – umanga iti, wawaenga...   
freq          423                                                423   

           Table_sub_name Breakdown                      Section    Units  \
count                2884      2884                         2884     2884   
unique                 10       130                           13       20   
top     A-wehenga ahumahi         -  Nga umanga katoa o Aotearoa  $(mano)   
freq                  936       221                          729      558   

       Value Time_Period Footnotes  
count   2884        2884      2884  
unique  1805          52        39  
top       15        2020    1 me 2  
freq      43         386       633

In [174]:
a1=['a','b','c','d','e']

In [175]:
a2=[1,2,3,4,5]

In [176]:
username=input("Enter Username")

Enter Username a


In [177]:
password=input("Enter password")

Enter password 1


In [178]:
import tkinter as tk
root=tk.Tk()
def main(): #function 
    root.title("my app")
    root.geometry("300x400")
    tk.Label(root,text='PIET College').pack()
    L1=tk.Label(root,text="Username").place(x=40,y=60)
    L2=tk.Label(root,text="Password").place(x=40,y=100)
    e1=tk.Entry(root)
    e1.place(x=100,y=60)
    e2=tk.Entry(root)
    e2.place(x=100,y=100)
    b1=tk.Button(root,text="SUBMIT",bg="green",command=show).place(x=130,y=150)
    b2=tk.Button(root,text="SIGNUP",bg="green",command=show1).place(x=130,y=190)
    
    root.mainloop()
    

In [179]:
def show():
    root=tk.Tk()
    root.config(bg="yellow")
    root.geometry("200x200")
    tk.Label(root,text="LOGIN").pack()
    root.mainloop()

In [180]:
def show1():
    root=tk.Tk()
    root.config(bg="red")
    root.geometry("300x200")
    tk.Label(root,text="SIGNUP").pack()
    L1=tk.Label(root,text="FIRST NAME").place(x=40,y=60)
    L2=tk.Label(root,text="LAST NAME").place(x=40,y=100)
    e1=tk.Entry(root)
    e1.place(x=100,y=60)
    e2=tk.Entry(root)
    e2.place(x=100,y=100)
    root.mainloop()

In [181]:
main()

In [182]:

#PANDAS OPERATIONS


In [183]:
df.shape

(4, 5)

In [232]:
df1.head()

C1  C2  C3  C4  C5
row1   1   2   3   4   5
row2   6   7   8   9  10
row3  11  12  13  14  15
row4  16  17  18  19  20

In [234]:
df1.tail()

C1  C2  C3  C4  C5
row1   1   2   3   4   5
row2   6   7   8   9  10
row3  11  12  13  14  15
row4  16  17  18  19  20

In [236]:
df1.describe()

C1         C2         C3         C4         C5
count   4.000000   4.000000   4.000000   4.000000   4.000000
mean    8.500000   9.500000  10.500000  11.500000  12.500000
std     6.454972   6.454972   6.454972   6.454972   6.454972
min     1.000000   2.000000   3.000000   4.000000   5.000000
25%     4.750000   5.750000   6.750000   7.750000   8.750000
50%     8.500000   9.500000  10.500000  11.500000  12.500000
75%    12.250000  13.250000  14.250000  15.250000  16.250000
max    16.000000  17.000000  18.000000  19.000000  20.000000

In [238]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, row1 to row4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C1      4 non-null      int64
 1   C2      4 non-null      int64
 2   C3      4 non-null      int64
 3   C4      4 non-null      int64
 4   C5      4 non-null      int64
dtypes: int64(5)
memory usage: 192.0+ bytes


In [240]:
df1

C1  C2  C3  C4  C5
row1   1   2   3   4   5
row2   6   7   8   9  10
row3  11  12  13  14  15
row4  16  17  18  19  20

In [242]:
#to EXTRACT a column
df1.C2

row1     2
row2     7
row3    12
row4    17
Name: C2, dtype: int64

In [244]:
#to EXTRACT a column
df1["C1"]

row1     1
row2     6
row3    11
row4    16
Name: C1, dtype: int64

In [257]:
#TO EXTRACT MULTIPLE COLUMN
df1[["C1","C2"]]

C1  C2
row1   1   2
row2   6   7
row3  11  12
row4  16  17

In [259]:
#CONDITIONAL OPERATIONS WITH THE HELP OF PANDAS
df1[df1["C2"]>2]

C1  C2  C3  C4  C5
row2   6   7   8   9  10
row3  11  12  13  14  15
row4  16  17  18  19  20

In [277]:
#writE EQN TO EXTRACT THE DATA FROM DF1  WHERE COLUMN 2  IS GREATER THAN TWO AND LESS THAN 17
df1[(df1["C2"] > 2) & (df1["C2"] < 17)]


C1  C2  C3  C4  C5
row2   6   7   8   9  10
row3  11  12  13  14  15

In [279]:
df

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [281]:
df1

C1  C2  C3  C4  C5
row1   1   2   3   4   5
row2   6   7   8   9  10
row3  11  12  13  14  15
row4  16  17  18  19  20

In [283]:
name=['a','b','c','d','e']

In [285]:
id=[1,2,3,4,5]

In [288]:
salary=[1000,2000,3000,4000,5000]

In [290]:
df=pd.DataFrame({"name":name,"emp_id":id,"salary":salary})

In [292]:
df

name  emp_id  salary
0    a       1    1000
1    b       2    2000
2    c       3    3000
3    d       4    4000
4    e       5    5000

In [294]:
df1.loc[["row2","row3"]] #data extract

C1  C2  C3  C4  C5
row2   6   7   8   9  10
row3  11  12  13  14  15

In [300]:
df.loc[[2,3]] #data extract


name  emp_id  salary
2    c       3    3000
3    d       4    4000

In [306]:
df1.iloc[1,2]

8

In [310]:
#add s new column in the existing dataset 
df["designation"] = ["hr","sde","da","ds","intern"]


In [312]:
df

name  emp_id  salary designation
0    a       1    1000          hr
1    b       2    2000         sde
2    c       3    3000          da
3    d       4    4000          ds
4    e       5    5000      intern

In [314]:
df["incentive"]=(df.salary)*0.1

In [316]:
df

name  emp_id  salary designation  incentive
0    a       1    1000          hr      100.0
1    b       2    2000         sde      200.0
2    c       3    3000          da      300.0
3    d       4    4000          ds      400.0
4    e       5    5000      intern      500.0

In [318]:
rank=[1,2,3,4,5,6,7,8,9,10]

In [322]:
name=["V KOHLI","S DHAWAN","ROHIT SHARMA","SURESH RAINA","DAVID WARNER","AB DE WILLIAMS","CHRIS GAYLE","MS DHONI","ROBIN UTHAPPA","GAUTAM GAMBHIR"]

In [324]:
matches=[207,194,213,205,150,184,142,220,193,154]


In [328]:
innings=[199,191,208,200,150,170,141,193,186,152]

In [330]:
runs=[6283,5784,5611,5528,5449,5162,4965,4746,4722,4217]

In [344]:
highest=[113,106,109,100,126,133,175,84,87,93]

In [346]:
hundreds=[5,2,1,1,4,3,6,0,0,0]

In [348]:
fifties=[42,44,40,39,50,40,31,23,25,36]

In [356]:
data = pd.DataFrame({"rank":rank,"name":name,"matches":matches,"innings":innings,"runs":runs,"highest":highest,"hundreds":hundreds,"fifties":fifties})

In [358]:
data[(data["innings"]>150) & (data["hundreds"]>=2) & (data["fifties"]>=35)]

rank            name  matches  innings  runs  highest  hundreds  fifties
0     1         V KOHLI      207      199  6283      113         5       42
1     2        S DHAWAN      194      191  5784      106         2       44
5     6  AB DE WILLIAMS      184      170  5162      133         3       40

In [370]:
data["bowl"] = data["matches"] - data["innings"]



In [372]:
data


rank            name  matches  innings  runs  highest  hundreds  fifties  \
0     1         V KOHLI      207      199  6283      113         5       42   
1     2        S DHAWAN      194      191  5784      106         2       44   
2     3    ROHIT SHARMA      213      208  5611      109         1       40   
3     4    SURESH RAINA      205      200  5528      100         1       39   
4     5    DAVID WARNER      150      150  5449      126         4       50   
5     6  AB DE WILLIAMS      184      170  5162      133         3       40   
6     7     CHRIS GAYLE      142      141  4965      175         6       31   
7     8        MS DHONI      220      193  4746       84         0       23   
8     9   ROBIN UTHAPPA      193      186  4722       87         0       25   
9    10  GAUTAM GAMBHIR      154      152  4217       93         0       36   

   bowl  
0     8  
1     3  
2     5  
3     5  
4     0  
5    14  
6     1  
7    27  
8     7  
9     2

In [374]:
df_new=data[data['hundreds']>0]
df_new

rank            name  matches  innings  runs  highest  hundreds  fifties  \
0     1         V KOHLI      207      199  6283      113         5       42   
1     2        S DHAWAN      194      191  5784      106         2       44   
2     3    ROHIT SHARMA      213      208  5611      109         1       40   
3     4    SURESH RAINA      205      200  5528      100         1       39   
4     5    DAVID WARNER      150      150  5449      126         4       50   
5     6  AB DE WILLIAMS      184      170  5162      133         3       40   
6     7     CHRIS GAYLE      142      141  4965      175         6       31   

   bowl  
0     8  
1     3  
2     5  
3     5  
4     0  
5    14  
6     1

In [376]:
#to rename
df_new.iloc[0,1]="VIRAt KOHLI"
df_new

rank            name  matches  innings  runs  highest  hundreds  fifties  \
0     1     VIRAt KOHLI      207      199  6283      113         5       42   
1     2        S DHAWAN      194      191  5784      106         2       44   
2     3    ROHIT SHARMA      213      208  5611      109         1       40   
3     4    SURESH RAINA      205      200  5528      100         1       39   
4     5    DAVID WARNER      150      150  5449      126         4       50   
5     6  AB DE WILLIAMS      184      170  5162      133         3       40   
6     7     CHRIS GAYLE      142      141  4965      175         6       31   

   bowl  
0     8  
1     3  
2     5  
3     5  
4     0  
5    14  
6     1

In [ ]:
#np.random randint function